fix: #38 Response error.role-not-found when Role not found
highsoft-shanghai/hare pull request #81
Opened 2023-05-09 06:31 UTC by raymond-liao

RT

2023-05-09 08:54 UTC, lynn518 submitted a review, later dismissed

2023-05-09 08:55 UTC, neilwangweili reviewed
Some advices

2023-05-09 08:55 UTC, neilwangweili commented on foundations/iam.domain/src/main/java/ltd/highsoft/hare/foundations/iam/domain/Roles.java
> +
```suggestion
```

2023-05-09 08:55 UTC, neilwangweili commented on foundations/iam.domain/src/main/java/ltd/highsoft/hare/foundations/iam/domain/Roles.java
> +
```suggestion
```

2023-05-09 08:55 UTC, neilwangweili commented on foundations/iam.domain/src/main/java/ltd/highsoft/hare/foundations/iam/domain/Roles.java
> +
```suggestion
```

2023-05-09 08:55 UTC, neilwangweili commented on foundations/iam.domain/src/main/java/ltd/highsoft/hare/foundations/iam/domain/Roles.java
> +
```suggestion
```

2023-05-09 08:55 UTC, neilwangweili commented on foundations/iam.gateways/src/main/java/ltd/highsoft/hare/foundations/iam/gateways/persistence/RoleMapper.java
>          String sql = "SELECT id, name, authorities, remarks, tenant_id, predefined, code FROM iam_roles WHERE id = :id";
role没有的情况在Roles里处理，业务逻辑不要落到gateways.persistence层

2023-05-09 08:55 UTC, neilwangweili commented on src/test/java/ltd/highsoft/hare/usecases/iam/GetRoleForUpdatingUseCaseTest.java
> +    public void should_throw_error_when_role_not_exists() {
error情况可以不用文档，不传，文档本来就是support正常情况

2023-05-09 09:00 UTC, raymond-liao commented on foundations/iam.domain/src/main/java/ltd/highsoft/hare/foundations/iam/domain/Roles.java
> +
idea 格式化自动加的

2023-05-09 09:00 UTC, raymond-liao commented on foundations/iam.domain/src/main/java/ltd/highsoft/hare/foundations/iam/domain/Roles.java
> +
idea 格式化自动加的

2023-05-09 09:03 UTC, raymond-liao commented on foundations/iam.gateways/src/main/java/ltd/highsoft/hare/foundations/iam/gateways/persistence/RoleMapper.java
>          String sql = "SELECT id, name, authorities, remarks, tenant_id, predefined, code FROM iam_roles WHERE id = :id";
这里应该要处理数据库查不到数据的情况

2023-05-09 09:04 UTC, raymond-liao commented on src/test/java/ltd/highsoft/hare/usecases/iam/GetRoleForUpdatingUseCaseTest.java
> +    public void should_throw_error_when_role_not_exists() {
也有道理啊

2023-05-09 09:22 UTC, neilwangweili requested changes
Need code review.

2023-05-09 09:23 UTC, neilwangweili commented on foundations/iam.domain/src/main/java/ltd/highsoft/hare/foundations/iam/domain/Roles.java
> +
需要统一一下idea格式化样式

2023-05-10 02:01 UTC, raymond-liao commented on foundations/iam.gateways/src/main/java/ltd/highsoft/hare/foundations/iam/gateways/persistence/RoleMapper.java
>          String sql = "SELECT id, name, authorities, remarks, tenant_id, predefined, code FROM iam_roles WHERE id = :id";
这个放着等聊清楚了再说吧

2023-05-10 16:28 UTC, neilwangweili commented on foundations/iam.application/src/main/java/ltd/highsoft/hare/foundations/iam/application/CreateRoleUseCase.java
> +        roles.save(role);
把roles看做成集合，集合没有save方法。集合用的是add

2023-05-10 16:38 UTC, merged